SET @col_exists = NULL;
SELECT COLUMN_NAME INTO @col_exists FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='payments' AND COLUMN_NAME='card_id';
SET @stmt = IF(@col_exists IS NULL, 'ALTER TABLE payments ADD COLUMN card_id INT DEFAULT NULL AFTER account_id', 'SELECT 1');
PREPARE stmt FROM @stmt; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SELECT COLUMN_NAME INTO @col_exists FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='payments' AND COLUMN_NAME='expense_id';
SET @stmt = IF(@col_exists IS NULL, 'ALTER TABLE payments ADD COLUMN expense_id INT DEFAULT NULL AFTER card_id', 'SELECT 1');
PREPARE stmt FROM @stmt; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SELECT COLUMN_NAME INTO @col_exists FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='expenses' AND COLUMN_NAME='due_day';
SET @stmt = IF(@col_exists IS NULL, 'ALTER TABLE expenses ADD COLUMN due_day INT DEFAULT NULL AFTER type', 'SELECT 1');
PREPARE stmt FROM @stmt; EXECUTE stmt; DEALLOCATE PREPARE stmt;

CREATE TABLE IF NOT EXISTS transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  account_id INT NOT NULL,
  type ENUM('income', 'expense') NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  description VARCHAR(255) DEFAULT '',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
